#!/bin/sh
set -u
cd /Users/sam/ai-agents
PY=.venv/bin/python
F='Backtest.run|bar/s|invalid value|c /= stddev|_function_base|UserWarning|bt = Backtest|warnings.warn'
echo "RUN RegimeTrendPullbackV2Crypto $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec /Users/sam/ai-agents/src/data/research_factory/specs/regime_v2/RegimeTrendPullbackV2Crypto.json --module /Users/sam/ai-agents/src/data/research_factory/strategies_v2/regime_539152b420_TrendPullbackStochastic.py 2>&1 | grep -vE "$F"
echo "RUN RegimeTrendPullbackV2Stocks $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec /Users/sam/ai-agents/src/data/research_factory/specs/regime_v2/RegimeTrendPullbackV2Stocks.json --module /Users/sam/ai-agents/src/data/research_factory/strategies_v2/regime_539152b420_TrendPullbackStochastic.py 2>&1 | grep -vE "$F"
echo "RUN RegimeTrendPullbackV2Indices $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec /Users/sam/ai-agents/src/data/research_factory/specs/regime_v2/RegimeTrendPullbackV2Indices.json --module /Users/sam/ai-agents/src/data/research_factory/strategies_v2/regime_539152b420_TrendPullbackStochastic.py 2>&1 | grep -vE "$F"
echo "RUN RegimeTrendPullbackV2Commod $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec /Users/sam/ai-agents/src/data/research_factory/specs/regime_v2/RegimeTrendPullbackV2Commod.json --module /Users/sam/ai-agents/src/data/research_factory/strategies_v2/regime_539152b420_TrendPullbackStochastic.py 2>&1 | grep -vE "$F"
echo "RUN RegimeTrendPullbackV2Forex $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec /Users/sam/ai-agents/src/data/research_factory/specs/regime_v2/RegimeTrendPullbackV2Forex.json --module /Users/sam/ai-agents/src/data/research_factory/strategies_v2/regime_539152b420_TrendPullbackStochastic.py 2>&1 | grep -vE "$F"
echo "RUN RegimeSqueezeTrendV2Crypto $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec /Users/sam/ai-agents/src/data/research_factory/specs/regime_v2/RegimeSqueezeTrendV2Crypto.json --module /Users/sam/ai-agents/src/data/research_factory/strategies_v2/regime_274f084b1d_SqueezeTrendGate.py 2>&1 | grep -vE "$F"
echo "RUN RegimeSqueezeTrendV2Stocks $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec /Users/sam/ai-agents/src/data/research_factory/specs/regime_v2/RegimeSqueezeTrendV2Stocks.json --module /Users/sam/ai-agents/src/data/research_factory/strategies_v2/regime_274f084b1d_SqueezeTrendGate.py 2>&1 | grep -vE "$F"
echo "RUN RegimeSqueezeTrendV2Indices $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec /Users/sam/ai-agents/src/data/research_factory/specs/regime_v2/RegimeSqueezeTrendV2Indices.json --module /Users/sam/ai-agents/src/data/research_factory/strategies_v2/regime_274f084b1d_SqueezeTrendGate.py 2>&1 | grep -vE "$F"
echo "RUN RegimeSqueezeTrendV2Commod $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec /Users/sam/ai-agents/src/data/research_factory/specs/regime_v2/RegimeSqueezeTrendV2Commod.json --module /Users/sam/ai-agents/src/data/research_factory/strategies_v2/regime_274f084b1d_SqueezeTrendGate.py 2>&1 | grep -vE "$F"
echo "RUN RegimeSqueezeTrendV2Forex $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec /Users/sam/ai-agents/src/data/research_factory/specs/regime_v2/RegimeSqueezeTrendV2Forex.json --module /Users/sam/ai-agents/src/data/research_factory/strategies_v2/regime_274f084b1d_SqueezeTrendGate.py 2>&1 | grep -vE "$F"
echo "RUN RegimePyramidTrendV2Crypto $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec /Users/sam/ai-agents/src/data/research_factory/specs/regime_v2/RegimePyramidTrendV2Crypto.json --module /Users/sam/ai-agents/src/data/research_factory/strategies_v2/regime_d0a4119045_PyramidTrendConvexity.py 2>&1 | grep -vE "$F"
echo "RUN RegimePyramidTrendV2Stocks $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec /Users/sam/ai-agents/src/data/research_factory/specs/regime_v2/RegimePyramidTrendV2Stocks.json --module /Users/sam/ai-agents/src/data/research_factory/strategies_v2/regime_d0a4119045_PyramidTrendConvexity.py 2>&1 | grep -vE "$F"
echo "RUN RegimePyramidTrendV2Indices $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec /Users/sam/ai-agents/src/data/research_factory/specs/regime_v2/RegimePyramidTrendV2Indices.json --module /Users/sam/ai-agents/src/data/research_factory/strategies_v2/regime_d0a4119045_PyramidTrendConvexity.py 2>&1 | grep -vE "$F"
echo "RUN RegimePyramidTrendV2Commod $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec /Users/sam/ai-agents/src/data/research_factory/specs/regime_v2/RegimePyramidTrendV2Commod.json --module /Users/sam/ai-agents/src/data/research_factory/strategies_v2/regime_d0a4119045_PyramidTrendConvexity.py 2>&1 | grep -vE "$F"
echo "RUN RegimePyramidTrendV2Forex $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec /Users/sam/ai-agents/src/data/research_factory/specs/regime_v2/RegimePyramidTrendV2Forex.json --module /Users/sam/ai-agents/src/data/research_factory/strategies_v2/regime_d0a4119045_PyramidTrendConvexity.py 2>&1 | grep -vE "$F"
echo "ALL_REGIME_RUNS_DONE $(date -u +%H:%M:%S)"
