#!/bin/sh
set -u
cd /Users/sam/ai-agents
PY=.venv/bin/python
F='Backtest.run|bar/s|invalid value|c /= stddev|_function_base|UserWarning|bt = Backtest|warnings.warn'
echo "RUN Turtle_crypto $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list16/Turtle_crypto.json --module src/data/research_factory/strategies_v2/turtle.py 2>&1 | grep -vE "$F"
echo "RUN Turtle_stocks $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list16/Turtle_stocks.json --module src/data/research_factory/strategies_v2/turtle.py 2>&1 | grep -vE "$F"
echo "RUN Turtle_indices $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list16/Turtle_indices.json --module src/data/research_factory/strategies_v2/turtle.py 2>&1 | grep -vE "$F"
echo "RUN Turtle_commod $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list16/Turtle_commod.json --module src/data/research_factory/strategies_v2/turtle.py 2>&1 | grep -vE "$F"
echo "RUN Turtle_forex $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list16/Turtle_forex.json --module src/data/research_factory/strategies_v2/turtle.py 2>&1 | grep -vE "$F"
echo "RUN DMA200_crypto $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list16/DMA200_crypto.json --module src/data/research_factory/strategies_v2/dma200.py 2>&1 | grep -vE "$F"
echo "RUN DMA200_stocks $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list16/DMA200_stocks.json --module src/data/research_factory/strategies_v2/dma200.py 2>&1 | grep -vE "$F"
echo "RUN DMA200_indices $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list16/DMA200_indices.json --module src/data/research_factory/strategies_v2/dma200.py 2>&1 | grep -vE "$F"
echo "RUN DMA200_commod $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list16/DMA200_commod.json --module src/data/research_factory/strategies_v2/dma200.py 2>&1 | grep -vE "$F"
echo "RUN DMA200_forex $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list16/DMA200_forex.json --module src/data/research_factory/strategies_v2/dma200.py 2>&1 | grep -vE "$F"
echo "RUN TSMOM_crypto $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list16/TSMOM_crypto.json --module src/data/research_factory/strategies_v2/tsmom.py 2>&1 | grep -vE "$F"
echo "RUN TSMOM_stocks $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list16/TSMOM_stocks.json --module src/data/research_factory/strategies_v2/tsmom.py 2>&1 | grep -vE "$F"
echo "RUN TSMOM_indices $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list16/TSMOM_indices.json --module src/data/research_factory/strategies_v2/tsmom.py 2>&1 | grep -vE "$F"
echo "RUN TSMOM_commod $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list16/TSMOM_commod.json --module src/data/research_factory/strategies_v2/tsmom.py 2>&1 | grep -vE "$F"
echo "RUN TSMOM_forex $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list16/TSMOM_forex.json --module src/data/research_factory/strategies_v2/tsmom.py 2>&1 | grep -vE "$F"
echo "RUN CarryTrend_crypto $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list16/CarryTrend_crypto.json --module src/data/research_factory/strategies_v2/carry_trend.py 2>&1 | grep -vE "$F"
echo "RUN gaps3+pairs pipeline $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode research-cycle --ideas-file src/data/research_factory/ideas_gaps3.txt --timeframe 4h --instruments BTC-USD ETH-USD SOL-USD 2>&1 | grep -vE "$F"
$PY src/agents/quant_research_agent.py --mode research-cycle --ideas-file src/data/research_factory/ideas_gaps3.txt --timeframe 1d --instruments AAPL MSFT JPM 2>&1 | grep -vE "$F"
$PY src/agents/quant_research_agent.py --mode research-cycle --ideas-file src/data/research_factory/ideas_gaps3.txt --timeframe 1d --instruments SPX NDX DJI 2>&1 | grep -vE "$F"
$PY src/agents/quant_research_agent.py --mode research-cycle --ideas-file src/data/research_factory/ideas_gaps3.txt --timeframe 1d --instruments WTI GLD SLV 2>&1 | grep -vE "$F"
$PY src/agents/quant_research_agent.py --mode research-cycle --ideas-file src/data/research_factory/ideas_gaps3.txt --timeframe 1d --instruments EURUSD USDJPY GBPUSD 2>&1 | grep -vE "$F"
echo "RUN allocation benchmark $(date -u +%H:%M:%S)"
$PY src/scripts/run_allocation_benchmark.py 2>&1 | grep -vE "$F"
echo "LIST16_DONE $(date -u +%H:%M:%S)"
