#!/bin/sh
set -u
cd /Users/sam/ai-agents
PY=.venv/bin/python
F='Backtest.run|bar/s|invalid value|c /= stddev|_function_base|UserWarning|bt = Backtest|warnings.warn'
echo "RUN Kalman_crypto $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/Kalman_crypto.json --module src/data/research_factory/strategies_v2/kalman.py 2>&1 | grep -vE "$F"
echo "RUN Kalman_stocks $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/Kalman_stocks.json --module src/data/research_factory/strategies_v2/kalman.py 2>&1 | grep -vE "$F"
echo "RUN Kalman_indices $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/Kalman_indices.json --module src/data/research_factory/strategies_v2/kalman.py 2>&1 | grep -vE "$F"
echo "RUN Kalman_commod $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/Kalman_commod.json --module src/data/research_factory/strategies_v2/kalman.py 2>&1 | grep -vE "$F"
echo "RUN Kalman_forex $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/Kalman_forex.json --module src/data/research_factory/strategies_v2/kalman.py 2>&1 | grep -vE "$F"
echo "RUN Markov_crypto $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/Markov_crypto.json --module src/data/research_factory/strategies_v2/markov.py 2>&1 | grep -vE "$F"
echo "RUN Markov_stocks $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/Markov_stocks.json --module src/data/research_factory/strategies_v2/markov.py 2>&1 | grep -vE "$F"
echo "RUN Markov_indices $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/Markov_indices.json --module src/data/research_factory/strategies_v2/markov.py 2>&1 | grep -vE "$F"
echo "RUN Markov_commod $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/Markov_commod.json --module src/data/research_factory/strategies_v2/markov.py 2>&1 | grep -vE "$F"
echo "RUN Markov_forex $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/Markov_forex.json --module src/data/research_factory/strategies_v2/markov.py 2>&1 | grep -vE "$F"
echo "RUN QuadMA_crypto $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/QuadMA_crypto.json --module src/data/research_factory/strategies_v2/quadma.py 2>&1 | grep -vE "$F"
echo "RUN QuadMA_stocks $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/QuadMA_stocks.json --module src/data/research_factory/strategies_v2/quadma.py 2>&1 | grep -vE "$F"
echo "RUN QuadMA_indices $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/QuadMA_indices.json --module src/data/research_factory/strategies_v2/quadma.py 2>&1 | grep -vE "$F"
echo "RUN QuadMA_commod $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/QuadMA_commod.json --module src/data/research_factory/strategies_v2/quadma.py 2>&1 | grep -vE "$F"
echo "RUN QuadMA_forex $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/QuadMA_forex.json --module src/data/research_factory/strategies_v2/quadma.py 2>&1 | grep -vE "$F"
echo "RUN BB27_crypto $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/BB27_crypto.json --module src/data/research_factory/strategies_v2/bb27.py 2>&1 | grep -vE "$F"
echo "RUN BB27_stocks $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/BB27_stocks.json --module src/data/research_factory/strategies_v2/bb27.py 2>&1 | grep -vE "$F"
echo "RUN BB27_indices $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/BB27_indices.json --module src/data/research_factory/strategies_v2/bb27.py 2>&1 | grep -vE "$F"
echo "RUN BB27_commod $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/BB27_commod.json --module src/data/research_factory/strategies_v2/bb27.py 2>&1 | grep -vE "$F"
echo "RUN BB27_forex $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/BB27_forex.json --module src/data/research_factory/strategies_v2/bb27.py 2>&1 | grep -vE "$F"
echo "RUN VolRegime_crypto $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/VolRegime_crypto.json --module src/data/research_factory/strategies_v2/volregime.py 2>&1 | grep -vE "$F"
echo "RUN VolRegime_stocks $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/VolRegime_stocks.json --module src/data/research_factory/strategies_v2/volregime.py 2>&1 | grep -vE "$F"
echo "RUN VolRegime_indices $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/VolRegime_indices.json --module src/data/research_factory/strategies_v2/volregime.py 2>&1 | grep -vE "$F"
echo "RUN VolRegime_commod $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/VolRegime_commod.json --module src/data/research_factory/strategies_v2/volregime.py 2>&1 | grep -vE "$F"
echo "RUN VolRegime_forex $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/VolRegime_forex.json --module src/data/research_factory/strategies_v2/volregime.py 2>&1 | grep -vE "$F"
echo "RUN VixRegime_stocks $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/VixRegime_stocks.json --module src/data/research_factory/strategies_v2/vixregime.py 2>&1 | grep -vE "$F"
echo "RUN VixRegime_indices $(date -u +%H:%M:%S)"
$PY src/agents/quant_research_agent.py --mode backtest-spec --spec src/data/research_factory/specs/list17/VixRegime_indices.json --module src/data/research_factory/strategies_v2/vixregime.py 2>&1 | grep -vE "$F"
echo "LIST17_DONE $(date -u +%H:%M:%S)"
